spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/coupon_example
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 100
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234